name: 'Socker Scan'
description: 'Scan a Docker image for vulnerabilities'

inputs:
  image-ref:
    description: 'The reference to the Docker image'
    required: true
    default: null

runs:
  using: 'composite'
  steps:
    # Extract image name from image-ref
    - name: Extract Image Name
      id: extract-image-name
      run: echo "${{ inputs.image-ref }}" | sed -E 's|^[^/]+/([^:]+):.*|IMAGE_NAME=\1|' | sed 's|/|-|g' >> $GITHUB_ENV
      shell: bash

    # Step to run Trivy vulnerability scanner on the specified Docker image
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.29.0
      with:
        scan-type: image
        image-ref: ${{ inputs.image-ref }}
        output: trivy-report-${{ env.IMAGE_NAME }}.json
        format: json
        exit-code: 0
        ignore-unfixed: true

    # Step to upload the vulnerability scan results as an artifact
    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@v4.6.0
      with:
        name: trivy-report-${{ env.IMAGE_NAME }}
        path: trivy-report-${{ env.IMAGE_NAME }}.json
        retention-days: 30
